var nameList = [
    {"name": "Sagar", "data": "super"},
    {"name": "Kowshik", "data": "beautiful"},
    {"name": "Praveen", "data": "bad"},
    {"name": "Arjun", "data": "amazing"},
    {"name": "Diya", "data": "awesome"},
    {"name": "Aakash", "data": "cool"},
    {"name": "Meera", "data": "wonderful"},
    {"name": "Aryan", "data": "fantastic"},
    {"name": "Neha", "data": "terrible"},
    {"name": "Rohan", "data": "superb"},
    {"name": "Aditi", "data": "excellent"},
    {"name": "Raj", "data": "splendid"},
    {"name": "Shreya", "data": "disappointing"},
    {"name": "Vikram", "data": "fabulous"},
    {"name": "Ishaan", "data": "disastrous"},
    {"name": "Anaya", "data": "brilliant"},
    {"name": "Riya", "data": "amazing"},
    {"name": "Dev", "data": "dreadful"},
    {"name": "Avni", "data": "stunning"},
    {"name": "Aarav", "data": "exemplary"},
    {"name": "Esha", "data": "splendid"},
    {"name": "Aadi", "data": "atrocious"},
    {"name": "Aanya", "data": "phenomenal"},
    {"name": "Vihaan", "data": "breathtaking"},
    {"name": "Ishika", "data": "splendid"},
    {"name": "Kabir", "data": "magnificent"},
    {"name": "Saanvi", "data": "fantastic"},
    {"name": "Advik", "data": "astonishing"},
    {"name": "Aarohi", "data": "spectacular"},
    {"name": "Reyansh", "data": "extraordinary"},
    {"name": "Aarna", "data": "dazzling"},
    {"name": "Ishan", "data": "splendid"},
    {"name": "Anika", "data": "wondrous"},
    {"name": "Advait", "data": "captivating"},
    {"name": "Kavya", "data": "divine"},
    {"name": "Rudra", "data": "splendid"},
    {"name": "Aadya", "data": "disgusting"},
    {"name": "Shivansh", "data": "impressive"},
    {"name": "Aarush", "data": "glorious"},
    {"name": "Anvi", "data": "awesome"},
    {"name": "Vivaan", "data": "extraordinary"},
    {"name": "Myra", "data": "phenomenal"},
    {"name": "Atharva", "data": "stunning"},
    {"name": "Ananya", "data": "spectacular"},
    {"name": "Vihaan", "data": "magnificent"},
    {"name": "Amaira", "data": "splendid"},
    {"name": "Aahana", "data": "amazing"},
    {"name": "Dhruv", "data": "disappointing"},
    {"name": "Anaya", "data": "brilliant"},
    {"name": "Veer", "data": "exquisite"},
    {"name": "Zara", "data": "splendid"},
    {"name": "Arnav", "data": "breathtaking"},
    {"name": "Nitya", "data": "dreadful"},
    {"name": "Reva", "data": "splendid"},
    {"name": "Ira", "data": "magnificent"},
    {"name": "Aarav", "data": "extraordinary"},
    {"name": "Anushka", "data": "breathtaking"},
    {"name": "Aarush", "data": "disastrous"},
    {"name": "Aadhya", "data": "spectacular"},
    {"name": "Aryan", "data": "impressive"},
    {"name": "Aaradhya", "data": "awesome"},
    {"name": "Ved", "data": "disappointing"},
    {"name": "Aisha", "data": "splendid"},
    {"name": "Shaurya", "data": "stunning"},
    {"name": "Tara", "data": "amazing"},
    {"name": "Vedant", "data": "fantastic"},
    {"name": "Aarush", "data": "brilliant"},
    {"name": "Trisha", "data": "extraordinary"},
    {"name": "Advaita", "data": "excellent"},
    {"name": "Avyan", "data": "dazzling"},
    {"name": "Avni", "data": "magnificent"},
    {"name": "Aayush", "data": "captivating"},
    {"name": "Ritvik", "data": "divine"},
    {"name": "Aanya", "data": "splendid"},
    {"name": "Vihaan", "data": "disgusting"},
    {"name": "Anya", "data": "impressive"},
    {"name": "Aarav", "data": "glorious"},
    {"name": "Navya", "data": "awesome"},
    {"name": "Yuvan", "data": "extraordinary"},
    {"name": "Aarna", "data": "phenomenal"},
    {"name": "Arjun", "data": "stunning"},
    {"name": "Ishita", "data": "spectacular"},
    {"name": "Aryan", "data": "magnificent"},
    {"name": "Aarna", "data": "splendid"},
    {"name": "Reyansh", "data": "amazing"},
    {"name": "Aarav", "data": "fantastic"},
    {"name": "Mira", "data": "brilliant"},
    {"name": "Arnav", "data": "exquisite"},
    {"name": "Saisha", "data": "splendid"},
    {"name": "Aadit", "data": "breathtaking"},
    {"name": "Tisha", "data": "impressive"},
    {"name": "Aaryan", "data": "gorgeous"},
    {"name": "Avani", "data": "splendid"},
    {"name": "Anay", "data": "stunning"},
    {"name": "Anika", "data": "amazing"},
    {"name": "Shlok", "data": "bad"},
]





export default function generate() {
   return  nameList[Math.floor( Math.random() * nameList.length )];
};


 